### ISSUE TITLE
Numba 0.57 compatibility issues

### ISSUE THREAD

**Issue by ZzEeKkAa** [IntelPython/numba-dpex#1000]
This is a meta Issue to evaluate numba-dpex with the upcoming numba 0.57 release (https://github.com/numba/numba/issues/8841)

Theses are blockers for compilation/import of numba_dpex:

- [x] Numba-dpex numba version checking does not handle tag names with `rc` postfix.
- [x] Numba-dpex has compatibility issue with `nrt_debug_print`
- [x] Numba-dpex relies on  module 'numba.core.utils' has no attribute 'cached_property'. Should be 'functools'
- [x] #1028

Tests not passing, so further actions needed. It may be a problem with missing Docker deps (since I've tested it in docker) or more global problems.

This is not full list. Possible issues may appear after resolving list above

**Comment by diptorupd** [comment]
Completed and numba-dpex now supports numba 0.57
