### ISSUE TITLE
Are `dpex.private.array`s always initialized with zeros ?

### ISSUE THREAD

**Issue by fcharras** [IntelPython/numba-dpex#1016]
I've been writing instructions for initialization of private arrays to all null values, but found out that my kernels work the same without the initialization step. It seems to behave as if private arrays are naturally initialized to zero. Seems to hold for both cpu and gpu devices. Is it something than can be assumed indeed ?

**Comment by diptorupd** [comment]
@fcharras That seems to be indeed the case. I was not aware or forgot :man_shrugging: 

Refer: https://github.com/IntelPython/numba-dpex/blob/000d5cd3aaf0f57db31c4142be0b5333fa0eb95a/numba_dpex/ocl/oclimpl.py#L501

The `alloca_once` is defined at:
https://github.com/numba/numba/blob/d44573b43dec9a7b66e9a0d24ef8db94c3dc346c/numba/core/cgutils.py#L362

To confirm, I wrote the following toy code:

```python
import numba_dpex as dpex
import dpnp


@dpex.kernel
def private_memory_kernel(A):
    i = dpex.get_global_id(0)
    prvt_mem = dpex.private.array(shape=10, dtype=dpnp.float32)
    for idx in range(10):
        prvt_mem[idx] = idx * idx
    dpex.barrier(dpex.LOCAL_MEM_FENCE)  # local mem fence
    for idx in range(10):
        A[i] += prvt_mem[idx]


N = 64
arr = dpnp.zeros(N, dtype=dpnp.float32)
orig = dpnp.arange(N, dtype=dpnp.float32)

private_memory_kernel[dpex.Range(N)](arr)

```
And the excerpt of the LLVM IR for the kernel has a `memset` instruction that does the zero initialization, and indeed confirms what you are seeing:

```llvm
; Function Attrs: alwaysinline
define internal spir_func i32 @dpex_py_devfn__5F__5F_main_5F__5F__2E_private_5F_memory_5F_kernel_24_1_2E_usm_5F_ndarray_28_dtype_3D_float32_2C__20_ndim_3D_1_2C__20_layout_3D_C_2C__20_address_5F_space_3D_1_2C__20_usm_5F_type_3D_device_2C__20_device_3D_level_5F_zero_3A_gpu_3A_0_2C__20_sycl_5F_device_3D__3C_dpctl_2E_SyclQueue_20_at_20_0x7f33e4888840_3E__29_(i8** nocapture %.ret, float addrspace(1)* %arg.A.0, float addrspace(1)* %arg.A.1, i64 %arg.A.2, i64 %arg.A.3, float addrspace(1)* %arg.A.4, i64 %arg.A.5.0, i64 %arg.A.6.0) #0 {
B0.endif.endif:
  %_dpex_pmem = alloca [10 x float], align 4
  %0 = bitcast [10 x float]* %_dpex_pmem to i8*
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 dereferenceable(40) %0, i8 0, i64 40, i1 false)
  %.15 = tail call spir_func i64 @_Z13get_global_idj(i32 0)
  br label %B40

...
```

**Comment by diptorupd** [comment]
Staring a bit harder at the LLVM IR, I am not convinced we are even allocating private memory. The `private.array` is allocated as a stack variable without any address space qualifier. The question is how is it treated by IGC. Let me dig a bit further by opening a separate issue.

**Comment by diptorupd** [comment]
Closing the issue as the original question has been answered.
