### ISSUE TITLE
UMAP fails due to unsupported reduction operation

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#103]
UMAP kernel fails due to the presence of a reduction operation in below kernel.

    result = 0.0
    for i in prange(x.shape[0]):
        result += (x[i] - y[i]) ** 2

**Comment by reazulhoque** [comment]
Reductions are not supported inside a parfor region.

**Comment by adarshyoga** [comment]
Duplicate of #71
