### ISSUE TITLE
Rambo overflow encountered in multiply warning

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#107]
The following kernel throws a overflow warning during execution.

@numba.jit(nopython=True, fastmath=True, parallel={'offload':True})
def vectmultiply(a, b):
    c = a * b
    return c[..., 0] - c[..., 1] - c[..., 2] - c[..., 3]

Warning:
rambo.py:135: RuntimeWarning: overflow encountered in multiply
  output_particles[..., 0] = X * D
rambo.py:136: RuntimeWarning: overflow encountered in multiply
  output_particles[..., 1:4] = numpy.repeat(X[..., numpy.newaxis], 3, axis=2) * C[..., 1:4]

This occurs only on the GPU. The parallelization on CPU does not throw the warning.

**Comment by diptorupd** [comment]
@adarshyoga is the issue still present?

**Comment by adarshyoga** [comment]
We do not use this function anymore. We can close this issue.
