### ISSUE TITLE
Document steps for release

### ISSUE THREAD

**Issue by ZzEeKkAa** [IntelPython/numba-dpex#1141]
Release process is pretty chalenging and requires:
- merging to `gold/*` branch
- tagging
- releasing changelog

We should document this process and define checklist for each release so it is just a technical process.

**Comment by diptorupd** [comment]
I had documented the steps that I follow: https://github.com/IntelPython/numba-dpex/wiki/Release-process

**Comment by diptorupd** [comment]
Closing the ticket based on the documentation created in the Wiki. Please reopen if there are any follow up questions.
