### ISSUE TITLE
Add implementation for numba_dpex.get_global_size()

### ISSUE THREAD

**Issue by roxx30198** [IntelPython/numba-dpex#1187]
Adding implementation for numba_dpex.get_global_size or any alternative for `q_ct1.get_device().get_info<cl::sycl::info::device::max_work_group_size>()`
would help us optimizing the implementation for device specific kernels instead of using a fixed size for all devices.

**Comment by diptorupd** [comment]
The Python bindings for a sub-set of the SYCL API is provided by `dpctl`. Numba-dpex only implements the small set of functions callable inside a kernel.

The property you want is already provided by `dpctl.SyclDevice`: https://intelpython.github.io/dpctl/latest/docfiles/dpctl/SyclDevice.html#dpctl.SyclDevice.max_work_group_size
