### ISSUE TITLE
NUMBA_DPEX_OPT doesn't work

### ISSUE THREAD

**Issue by roxx30198** [IntelPython/numba-dpex#1226]
Macro for turning the llvm optimization level doesn't work as expected. For any value of `NUMBA_DPEX_OPT`, it takes the default optimization level and not the one provided through this environment variable.
`NUMBA_OPT` works as expected.

**Comment by diptorupd** [comment]
@roxx30198 can you please provide some more detail? I am unable to replicate the issue.

**Comment by diptorupd** [comment]
@roxx30198 based on triaging the issue together today and identifying the issue to be caused by the conda env that had an older numba-dpex installed, I am closing the issue. Please reopen if you see it happening again.
