### ISSUE TITLE
Provide list of all NumPy functions that are supported on the GPU

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#128]
We should have a table indicating what NumPy functions we support on teh GPU and how the support is implemented.

**Comment by reazulhoque** [comment]
Should we place the table in the wiki?

**Comment by diptorupd** [comment]
No, we should provide it in a future github pages documentation similar to what dpnp does https://intelpython.github.io/dpnp/reference/comparison.html#

**Comment by reazulhoque** [comment]
This PR: https://github.com/IntelPython/numba-dppy/pull/231 initiates that process by trying to automatically generate documentation and scaffoldings needed.

**Comment by diptorupd** [comment]
NumPy is no longer supported. A new issue to track dpnp support will be created.
