### ISSUE TITLE
Create array item reference type to handle pass by reference cases

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#1316]
Some functions like the `AtomicRef` constructor and `compare_exchange` require arguments be passed by reference since these functions end up modifying the reference arguments. This pass by reference is currently handled by passing a reference to the array object along with the index to the item which needs to be passed by reference, like in the snippet below.

`b_atomic_ref = AtomicRef(b, index=1)`

A more elegant approach would be to introduce a `Ref` type to store a array item reference that contains both the array and the index as members. This array item reference type can be used where pass by reference is needed. See example code snippet below.

```python
b = dpnp.ones(10)
b_ref = Ref(ref=b, index=1)
b_atomic_ref = AtomicRef(b_ref)
```

**Comment by diptorupd** [comment]
@adarshyoga this change is mostly syntactic sugar and let us not bother at this time. I will update the `AtomicRef` docs to be more clear as to what is happening when we pass an array and an index to the `AtomicRef` constructor.
