### ISSUE TITLE
Fill registry with functions, getattrs, setattrs, casts and constants

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#142]
For all Numpy identifiers that have been registered for typing in Numba... this registry contains functions, getattrs, setattrs, casts and constants...

In `numba_register_lower_builtin()`.

_Originally posted by @diptorupd in https://github.com/IntelPython/numba-dppy/pull/50#r540370933_

**Comment by diptorupd** [comment]
This looks more like a comment than an issue.
