### ISSUE TITLE
Error during installation with conda: FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

### ISSUE THREAD

**Issue by DerBrecher** [IntelPython/numba-dpex#1480]
During installation of I encounter an error when following the install instructions given here:
[https://intelpython.github.io/numba-dpex/latest/getting_started.html](https://intelpython.github.io/numba-dpex/latest/getting_started.html)

Running:
`conda create -n numba-dpex-env                                             \
    numba-dpex dpnp dpctl dpcpp-llvm-spirv                                 \
    -c dppy/label/dev -c intel -c conda-forge`

leads to the following error message:
`Channels:
 - dppy/label/dev
 - intel
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
`

Trying to access [https://conda.anaconda.org/intel](https://conda.anaconda.org/intel) in a browser only redirects to [https://anaconda.org/](https://anaconda.org/)

I encounter a similar error when trying to install the Intel Extension for PyTorch.

**Comment by diptorupd** [comment]
@xaleryb can you please take a look?

**Comment by ZzEeKkAa** [comment]
We need to switch to conda-forge completely without `intel` channel

**Comment by ZzEeKkAa** [comment]
However, there is a blocker - we are missing `mkl-dpcpp` package in `conda-forge`: https://github.com/conda-forge/intel_repack-feedstock/issues/75

**Comment by ZzEeKkAa** [comment]
Actually, `mkl-dpcpp` is just a meta package that contains dependencies. Instead dpnp must depend only on those it uses.

**Comment by xaleryb** [comment]
@DerBrecher, could you please try to replace "-c intel" with "-c https://software.repos.intel.com/python/conda"?

**Comment by DerBrecher** [comment]
@xaleryb the fix worked worked for numba-dpex! Thank you.
I tried the same for the Intel Extension for PyTorch but it failed there. Guess I will open a ticket there.

**Comment by xaleryb** [comment]
@DerBrecher thanks for checking that. Please use this solution for now since intel channel is not stable for now and new channel was specifically created to cover that gap.

I'll close this ticket if there are no concerns from your end.
