### ISSUE TITLE
Can't install using conda

### ISSUE THREAD

**Issue by chillenb** [IntelPython/numba-dpex#1481]
```
$ conda install numba-dpex -c intel -c conda-forge
Channels:
 - intel
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations
```

**Comment by ZzEeKkAa** [comment]
As was mentioned [here](https://github.com/IntelPython/numba-dpex/issues/1480#issuecomment-2230025965), please try to replace "-c intel" with "-c https://software.repos.intel.com/python/conda"

**Comment by diptorupd** [comment]
@chillenb I have updated the README and Getting stated page to mention the new channel that should be used instead of the `intel` channel on anaconda.com.

**Comment by chillenb** [comment]
Thanks for doing that! I guess this issue can be closed
