### ISSUE TITLE
Add support for atomic operations inside a kernel

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#161]
Need to support min, max, nanmin, nanmax, compare_and_swap for int, float and uint types.

**Comment by diptorupd** [comment]
@reazulhoque ping!

**Comment by diptorupd** [comment]
All atomic function supported by SYCL have corresponding versions implemented in the kernel_api with spir-v overloads. nanmin and nanmax are not being considered at this point in time.
