### ISSUE TITLE
It is necessary to implement the elements of the data transfer

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#162]
We need analogs of the following functions in сuda:

- [ ] numba.cuda.device_array 
- [ ] numba.cuda.device_array_like 
- [ ] numba.cuda.to_device 
- [ ] numba.cuda.as_cuda_array (Create a DeviceNDArray from any object that implements the cuda array interface.) 
- [ ] numba.cuda.is_cuda_array

**Comment by diptorupd** [comment]
All these functionality are handled in `dpctl.tensor.usm_ndarray`. Numba-dpex will not implement its own array container.
