### ISSUE TITLE
Implement mechanism of the Device arrays

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#163]
We need something like cuda  numba.cuda.cudadrv.devicearray.DeviceNDArray 
and follow features:
- [ ] copy_to_host 
- [ ] is_c_contiguous 
- [ ] is_f_contiguous 
- [ ] ravel 
- [ ] reshape

**Comment by diptorupd** [comment]
The feature is currently supported in the Kernel API using `dpctl.tensor.usm_ndarray`. numba-dpex will not provide its own array data type.
