### ISSUE TITLE
Example for sum reduction with local memory and barriers

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#186]
GPU Reduction section of docs contain line:
> Examples show invocation of the kernel multiple times.
Reduction could be implemented by invoking the kernel once, but that requires
support for local device memory and barrier, which is a work in progress.

If local memory and barriers are supported now then we need to implement the corresponding example.

**Comment by diptorupd** [comment]
The examples are to be found in numba_dpex/examples/kernel
