### ISSUE TITLE
Implement changing the dpctl.device_context to CPU while debugging

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dpex#198]
We can use python debugger (PDB) to debug kernels.
dppy.kernel can be debugged by changing the dpctl.device_context to CPU.

**Comment by diptorupd** [comment]
Device context is deprecated and set to be removed for kernels. We can achieve the desired behavior by using USM-based arrays (dpnp, dpctl.tensor.usmndarray) and setting the device where the arrays are allocated to "cpu".
