### ISSUE TITLE
Function of getting the absolute size (or shape) in work-items

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dpex#200]
Do we have equivalent for `numba.cuda.gridsize(ndim)`?

**Comment by diptorupd** [comment]
The feature is now present in `kernel_api`. `NdItem.get_global_range(dimension)` https://intelpython.github.io/numba-dpex/latest/autoapi/numba_dpex/kernel_api/index.html#numba_dpex.kernel_api.NdItem.get_global_range
