### ISSUE TITLE
Tests for dpnp functions calls without check for results

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#212]
Tests for dpNP functions calls without check for results

I think we need to check that dpnp function was called. 
We do not have to check results.
dpNP has its own tests for these function results.

We need to check that function is present and could be called with different data types.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/numba-dppy/pull/141#r565303451_

**Comment by diptorupd** [comment]
All overloads that involved generating calls to dpnp backend have been removed. As such the issue is not relevant right now, but should be kept in mind as a unit test design paradigm when dpnp overloads are reintroduced.
