### ISSUE TITLE
Try to eliminate code duplication in common_impl_* functions

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#213]
It seems like code duplication.
Only calling for `dpnp_funct()` with different args are different.
Can we somehow eliminate duplication?

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/numba-dppy/pull/141#discussion_r564590950_

**Comment by diptorupd** [comment]
the earlier numpy overloads are completely removed and are getting redesigned for the dpnp library using oneMKL.
