### ISSUE TITLE
Cython interface for numba-dppy and dpnp integration

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#221]
The same approach like [numba-scipy](https://github.com/numba/numba-scipy).

Implementation from dpnp side - https://github.com/IntelPython/dpnp/pull/497

The interface will reduce a lot of code duplication in numba-dppy. Numba-dppy will use from dpnp and will not contain in its code:
1. Enum of dpnp functions (DPNPFuncName)
2. dpnp function names
3. dpnp function signatures

Possibly map for numpy-to-dpnp functions will also be on the side of dpnp.

Related issues:
- [ ] https://github.com/IntelPython/numba-dppy/issues/213
- [ ] https://github.com/IntelPython/numba-dppy/issues/212

**Comment by diptorupd** [comment]
Marking this as out of scope. The latest dpnp has deprecated the C-API backend library and started using pybind11. We do not expect to create a Cython interface to dpnp for numba-dpex. Alternative approaches may need to be explored for better dpnp and numba-dpex integration.
