### ISSUE TITLE
Preview generated documentation for each PRs which change documentation

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#240]
https://github.com/IntelPython/numba-dppy/pull/232
Links:
- https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
- https://github.com/actions/upload-artifact
- https://github.com/oneapi-src/oneAPI-spec/blob/main/.github/workflows/ci.yml
- https://github.com/data-apis/array-api/blob/main/.github/workflows/pages.yml

**Comment by diptorupd** [comment]
Done.
