### ISSUE TITLE
Integrate `__sycl_usm_array_interface__` inside `numba_dppy`

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dpex#250]
Our goal is to have zero copy data movement, if an array conforms to `_sycl_usm_array_interface__`. We have three paths of code dispatching to the GPU:

- `@njit`
    - [ ] Evaluate any incoming argument to see if it implements `_sycl_usm_array_interface__`. If yes, zero copy to `numpy_usm_shared`. If no, create a `numpy_usm_shared` array and copy that data.
    - [ ] Check at lowering whether we have an instance of `numpy_usm_shared` and act accordingly. If the point above is implemented this will always be true. (proposed implementation [PR](https://github.com/IntelPython/numba-dppy/pull/248)).

-  `@dppy.kernel`
    - [x] Evaluate any incoming argument to see if it implements `_sycl_usm_array_interface__`. If yes, zero copy to `numpy_usm_shared`. If no, create a `numpy_usm_shared` array and copy that data.

- Third party library calls (e.g. dpnp)
    - [x] Evaluate any incoming argument to see if it implements `_sycl_usm_array_interface__`. If yes, zero copy to `numpy_usm_shared`. If no, create a `numpy_usm_shared` array and copy that data. This check should happen in the pass proposed at [PR](https://github.com/IntelPython/numba-dppy/pull/190).

**Comment by reazulhoque** [comment]
Implemnetation for `@dppy.kernel` is completed through this PR: https://github.com/IntelPython/numba-dppy/pull/629

**Comment by diptorupd** [comment]
`njit` decorator (`dpjit`) will only support `dpnp.ndarray` and not any generic array object with `__sycl_usm_array_interface__`. Kernels already properly support `__sycl_usm_array_interface__`.
