### ISSUE TITLE
Completing the integration with dpnp to support NumPy operations.

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#253]
5. NumPy support completed.
P1
Reazul
Need to estimate work.
EOY goal.
Contains as part https://github.com/orgs/IntelPython/projects/3#card-52649497

Related issues:
Old Analysis:
- Numpy array creation analysis #210 
- Numpy array ops analysis #209 

Implementation:
- Array creations implementation #254
- Array ops implementation #255

**Comment by diptorupd** [comment]
The issue of supporting dpnp functions inside `dpjit` is ongoing work, but this ticket can be closed as it is not clear enough.
