### ISSUE TITLE
Provide easily distinguishable kernel names

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#260]
The names set by Numba-dppy for kernels generated from parfors are extremely long and make it impossible to determine what parfor they represent in the source code. Having easily distinguishable kernel names is extremely useful performance analysis of programs that have multiple kernels.

For easily distinguishable kernel names, I suggest the following protocol.
<file_name:function_name:line_number>
This combination is going to be unique for each kernel. If a parfor is called from outside a function, then it can be omitted and the combination of file_name and line_number (<file_name:line_number>) will still be unique.

**Comment by diptorupd** [comment]
@adarshyoga I agree we need to fix the naming. The current naming is basically useless.

Expanding on your proposal, I suggest the following:

1. Kernel name is a combination of the actual function name + a UUID that is based on the argument types.
2. Parfor kernels follow the convention of function_name+loc+ UUID based on argument types
3. Every kernel adds a metadata to LLVM IR showing the argument types

Can you help implement a solution? We can try and get it into 0.20?
