### ISSUE TITLE
NUMBA_DPPY_OFFLOAD_DIAGNOSTICS always prints out level 4 diagnostics irrespective of diagnostics level.

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#284]
Numba-dppy always prints out level 4 diagnostics for the NUMBA_DPPY_OFFLOAD_DIAGNOSTICS option even if we set the flag value to 1,2, or 3.

**Comment by PokhodenkoSA** [comment]
@1e-to Could you check please?

**Comment by diptorupd** [comment]
Closing this as the parfor offload is now deemed experimental.
