### ISSUE TITLE
Development mode works only in source folder

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#292]
```bash
$ cd numba-dppy  # go to source folder
$ python setup.py develop
$ python -c "import numba_dppy; print(numba_dppy.__file__)"
/localdisk/work/spokhode/numba-dppy/numba_dppy/__init__.py
```
`numba_dppy` from source folder.

```bash
$ cd numba-dppy/..  # go out from source folder
$ python -c "import numba_dppy; print(numba_dppy.__file__)"
/localdisk/work/spokhode/miniconda3/envs/numba-dev/lib/python3.7/site-packages/numba_dppy/__init__.py
```
`numba_dppy` from conda environment.

`numba` behaves like current folder does not matter.

**Comment by Alexander-Makaryev** [comment]
it's not a bug but a feature)
When you import a package in Python, it tries to find it in several places one by one like a priority list.
First of all it looks in current directory, then in $PYTHONPATH, Python environment, easy-install.pth etc(?) 
Google says that it is possible to manipulate with this order using `sys.path`.

In your case I suggest to just uninstall same package (same package as you are setup in develop mode) from environment.

**Comment by PokhodenkoSA** [comment]
> In your case I suggest to just uninstall same package (same package as you are setup in develop mode) from environment.

For `numba` I am not required to remove package from environment.

**Comment by PokhodenkoSA** [comment]
Сщгдв и

**Comment by diptorupd** [comment]
Can not replicate in current main.
