### ISSUE TITLE
DevOps ideas

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#300]
- [ ] Code quality:
 https://codeclimate.com/ (example https://codeclimate.com/github/numba/llvmlite)
- [x] Coverage: 
https://coveralls.io/ (example https://coveralls.io/github/numba/llvmlite)
#621 
- [ ] Documentation:
https://readthedocs.org/ (example https://llvmlite.readthedocs.io/en/latest/)

**Comment by diptorupd** [comment]
codeclimate asks for money, coverage is complete and we have no plans to migrate to readthedocs for now
