### ISSUE TITLE
Missing Code comments in most of the numba_dpex samples in the examples folder

### ISSUE THREAD

**Issue by praveenkk123** [IntelPython/numba-dpex#319]
Most of the code samples in numba_dppy/examples folders are missing code comments. Can you please add detailed code comments where necessary to have a better understanding of the examples

**Comment by PokhodenkoSA** [comment]
Thank you for mentioning it. We will update examples with more comments.
For better understanding of numba_dppy I would recommend to start from documentation https://intelpython.github.io/numba-dppy/.
Actually numba_dppy/examples are used for illustrating documentation with code.
Sure examples will be better if become standalone learning materials.
