### ISSUE TITLE
Level-0 fails with SyclProgramCompilationError when debugger is on

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dpex#322]
For some reason "level0" fails with "SyclProgramCompilationError" when debug is activated (`export NUMBA_DPPY_DEBUG=1`).

PR with tests: https://github.com/IntelPython/numba-dppy/pull/297

**Comment by reazulhoque** [comment]
@akharche The PR seems merged. Were we skipping the test for level0? Please specify the test and the commnad to replicate the error.

**Comment by akharche** [comment]
@reazulhoque To reproduce an error you can try sum example (https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/examples/sum.py#L56)
`NUMBA_DPPY_DEBUG=1 python sum.py`

**Comment by PokhodenkoSA** [comment]
Need to check with latest debugger.

**Comment by diptorupd** [comment]
@roxx30198 Please retest the issue. The problem seems to be with GDB debugging on a `level_zero:gpu` device. You can use devcloud to test on a recent generation graphics card and Gen9 integrated graphics cards are no longer supported by latest GDB.

**Comment by diptorupd** [comment]
@ZzEeKkAa Have you encountered any issue like this recently when testing GDB tests on a level zero device?

**Comment by ZzEeKkAa** [comment]
@diptorupd no, not with latest branch. Since we made tests pass on level zero gpu except shutdown freeze, that means that program was compiled successfully and this issue may be closed.
