### ISSUE TITLE
Sort all imports

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#335]
@PokhodenkoSA @reazulhoque @akharche @1e-to @DrTodd13 @vlad-perevezentsev 

VS Code has the nice feature to sort imports alphabetically. Is this a style that we should standardize?

**Comment by PokhodenkoSA** [comment]
Sorting imports ABC is not correct. [PEP-8](https://www.python.org/dev/peps/pep-0008/#imports):
> Imports should be grouped in the following order:
> 1. Standard library imports.
> 2. Related third party imports.
> 3. Local application/library specific imports.
>
> You should put a blank line between each group of imports.

flake8 help to find correct order issues. Also [isort](https://pypi.org/project/isort/) is an auto tool for it.

**Comment by diptorupd** [comment]
Can we closed as we moved to isort a while back.
