### ISSUE TITLE
Do we envision supporting strides and non-C contiguous data layouts?

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#363]
Do we envision supporting strides and non-C contiguous data layouts?

_Originally posted by @diptorupd in https://github.com/IntelPython/numba-dppy/pull/287#r617173732_

**Comment by PokhodenkoSA** [comment]
@diptorupd
What ideas do you have about it?

**Comment by diptorupd** [comment]
@PokhodenkoSA Numba supports strides and `dpctl.tensor.usm_ndarray` supports strides. I plan to work to add support for strides in `kernel` first and then `njit`. However, the changes for strides will happen post 2021.3.

**Comment by diptorupd** [comment]
Strides and non-C contiguous layout now work as expected. The new feature has been verified by unit tests added on #1285
