### ISSUE TITLE
Not clear error message

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dpex#38]
The error message `""Importing numba-dppy failed""` defines that probably something wrong with GPU devices. 
The message could be confusing for users because it is not informative

**Comment by PokhodenkoSA** [comment]
@akharche Could you provide please how to reproduce it?

**Comment by akharche** [comment]
@PokhodenkoSA I think this message arises when something wrong with GPU driver, may be when appropriate driver is absent. Now this message is `"Importing numba-dppy failed"`

**Comment by akharche** [comment]
The problem also reproduces when a user not in a "video" group on a machine, for this reason he does not have access to GPU device. 
But the error is confusing to check whether numba-dppy is installed or not.

**Comment by diptorupd** [comment]
The issue was fixed with latest kernel refactoring.
