### ISSUE TITLE
In examples recommend another way to change default device

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#438]
SYCL_DEVICE_FILTER - filters, not actually change default device.
Do not recommend users to use it. It is not the best recommendation but there is no other way to change default device yet.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/numba-dppy/pull/428#discussion_r649200070_

**Comment by diptorupd** [comment]
Not clear what the issue is about.
