### ISSUE TITLE
Build with dpnp but do not require dpnp in runtime

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#506]
Goal: Enable dpnp support does not mean numba-dppy can not run without dpnp.
It will eliminate complex dpnp dependencies (i.e. MKL) in numba-dppy CI and other scenarios.

**Comment by diptorupd** [comment]
True for kernel decorator, but the new `dpjit` decorator will make dpnp support an explicit user-visible feature. Thus, dpnp needs to be a runtime dependency as dpex' evolves in a dpnp compiler.
