### ISSUE TITLE
Update versioneer

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#531]
https://github.com/python-versioneer/python-versioneer

Current: 0.19
Latest: 0.20

**Comment by diptorupd** [comment]
@PokhodenkoSA see https://github.com/IntelPython/dpctl/issues/651. We should stop vendoring versionner and rely on the versioneer package.

**Comment by PokhodenkoSA** [comment]
> @PokhodenkoSA see [IntelPython/dpctl#651](https://github.com/IntelPython/dpctl/issues/651). We should stop vendoring versionner and rely on the versioneer package.

I agree. There should be better alternative.

**Comment by diptorupd** [comment]
Updated to 0.28. Currently, we are not planning to vendor `versioneer`
