### ISSUE TITLE
test_usm_ndarray_interop fails without gpu

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#533]
test_usm_ndarray_interop gpu doesn't skip when there is no dpnp in environment (Windows)

Example: https://github.com/1e-to/numba-dppy/pull/1/checks?check_run_id=3533839223#step:13:1101

**Comment by diptorupd** [comment]
The test was redesigned to now use `dpctl.tensor.usm_ndarray` and supports both windows and linux.
