### ISSUE TITLE
Fix documentation warnings 

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#539]
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:28: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:31: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:33: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:33: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:40: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:42: WARNING: Unexpected section title.

data_parallel_sum[len(a), dppy.DEFAULT_LOCAL_SIZE](dA, dB, dC)
---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:55: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:58: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:62: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:64: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:64: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:134: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:136: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:156: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:156: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:152: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:153: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:154: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:155: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:156: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:157: WARNING: Inline substitution_reference start-string without end-string.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:163: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:170: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:209: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:209: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:224: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:230: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:244: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:250: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/__init__.py:docstring of numba_dppy:250: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/compiler.py:docstring of numba_dppy.compiler.compile_with_dppy:8: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/compiler.py:docstring of numba_dppy.compiler.compile_with_dppy:9: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/docs/apidoc/numba_dppy.dpnp_glue.rst:7: WARNING: duplicated entry found in toctree: apidoc/numba_dppy.dpnp_glue.dpnp_fptr_interface
/localdisk/work/etotmeni/numba-dppy/numba_dppy/dppy_lowerer.py:docstring of numba_dppy.dppy_lowerer.DPPYLower.lower:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/dppy_lowerer.py:docstring of numba_dppy.dppy_lowerer.DPPYLower.lower:15: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: __all__ should be a list of strings, not [<class 'numba_dppy.driver.dpctl_capi_fn_builder.DpctlCAPIFnBuilder'>, <class 'numba_dppy.driver.kernel_launch_ops.KernelLaunchOps'>, <class 'numba_dppy.driver.usm_ndarray_type.USMNdArrayType'>] (in module numba_dppy.driver) -- ignoring __all__
/localdisk/work/etotmeni/numba-dppy/numba_dppy/driver/kernel_launch_ops.py:docstring of numba_dppy.driver.kernel_launch_ops.KernelLaunchOps.process_kernel_arg:8: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/driver/kernel_launch_ops.py:docstring of numba_dppy.driver.kernel_launch_ops.KernelLaunchOps.process_kernel_arg:9: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/driver/kernel_launch_ops.py:docstring of numba_dppy.driver.kernel_launch_ops.KernelLaunchOps.process_kernel_arg:12: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/driver/usm_ndarray_type.py:docstring of numba_dppy.driver.usm_ndarray_type.USMNdArrayType:4: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:6: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:8: WARNING: Unexpected section title.

Numba IR Before Rewrite:
---------------------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:13: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:15: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:17: WARNING: Unexpected section title.

Numba IR After Rewrite:
---------------------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:23: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/rename_numpy_functions_pass.py:docstring of numba_dppy.rename_numpy_functions_pass.RewriteNumPyOverloadedFunctions.run:25: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------------------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/target.py:docstring of numba_dppy.target.DPPYTargetContext.get_ufunc_info:8: WARNING: Unexpected section title.

Parameters
----------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/target.py:docstring of numba_dppy.target.DPPYTargetContext.get_ufunc_info:12: WARNING: Unexpected section title.

Returns
-------
/localdisk/work/etotmeni/numba-dppy/numba_dppy/target.py:docstring of numba_dppy.target.DPPYTargetContext.insert_const_string:7: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/__init__.py:docstring of numba_dppy.utils.array_utils.as_usm_obj:13: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/__init__.py:docstring of numba_dppy.utils.array_utils.as_usm_obj:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/__init__.py:docstring of numba_dppy.utils.array_utils.copy_from_numpy_to_usm_obj:13: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/__init__.py:docstring of numba_dppy.utils.array_utils.copy_from_numpy_to_usm_obj:18: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/__init__.py:docstring of numba_dppy.utils.array_utils.copy_to_numpy_from_usm_obj:7: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/__init__.py:docstring of numba_dppy.utils.llvm_codegen_helpers.get_llvm_type:6: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/array_utils.py:docstring of numba_dppy.utils.array_utils.as_usm_obj:13: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/array_utils.py:docstring of numba_dppy.utils.array_utils.as_usm_obj:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/array_utils.py:docstring of numba_dppy.utils.array_utils.copy_from_numpy_to_usm_obj:13: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/array_utils.py:docstring of numba_dppy.utils.array_utils.copy_from_numpy_to_usm_obj:18: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/array_utils.py:docstring of numba_dppy.utils.array_utils.copy_to_numpy_from_usm_obj:7: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/utils/llvm_codegen_helpers.py:docstring of numba_dppy.utils.llvm_codegen_helpers.get_llvm_type:6: WARNING: Definition list ends without a blank line; unexpected unindent.
/localdisk/work/etotmeni/numba-dppy/numba_dppy/vectorizers.py:docstring of numba_dppy.vectorizers.DPPYUFuncMechanism.call:3: WARNING: Unexpected indentation.
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/index.rst:34: WARNING: Title underline too short.

Example of Intel® Distribution for GDB* usage
--------------------------------------------
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/index.rst:34: WARNING: Title underline too short.

Example of Intel® Distribution for GDB* usage
--------------------------------------------
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/index.rst:21: WARNING: Unknown target name: "intel® distribution for gdb* product page".
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/local_variables.rst:57: WARNING: Title underline too short.

``print <variable>``
------------------
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/local_variables.rst:57: WARNING: Title underline too short.

``print <variable>``
------------------
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/local_variables.rst:71: WARNING: Title underline too short.

``ptype <variable>``
------------------
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/local_variables.rst:71: WARNING: Title underline too short.

``ptype <variable>``
------------------
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/debugging/set_up_machine.rst:10: WARNING: Unknown target name: "intel® oneapi toolkits installation guide for linux* os / install intel gpu drivers".
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/kernel_programming_guide/ufunc.rst:21: WARNING: Object named 'test_ufunc' not found in include file '/localdisk/work/etotmeni/numba-dppy/numba_dppy/examples/vectorize.py'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /localdisk/work/etotmeni/numba-dppy/docs/apidoc/modules.rst: WARNING: document isn't included in any toctree
/localdisk/work/etotmeni/numba-dppy/docs/user_guides/kernel_programming_guide/random.rst: WARNING: document isn't included in any toctree

**Comment by diptorupd** [comment]
out of date.
