### ISSUE TITLE
Refactoring ideas tracker

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#636]
@diptorupd @reazulhoque @1e-to 
This ticket is for collecting issues with ideas and proposals for code improvements.
All issues will be with following label: [code-cleanup](https://github.com/IntelPython/numba-dppy/labels/code%20cleanup)

- [x] #635 
- [x] #633 
- [ ] ...

**Comment by diptorupd** [comment]
Both tasks have been completed.
