### ISSUE TITLE
Some numpy_usm_shared registrations are failing eval.

### ISSUE THREAD

**Issue by DrTodd13** [IntelPython/numba-dpex#64]
In numpy_usm_shared where we iterate through functions and register them with Numba, we do an eval of the function name and for now some of those are failing.  I added try/except around the eval so we can skip ones that fail eval for now but we need to fix this soon.

**Comment by diptorupd** [comment]
Closing as `numpy_usm_shared` is slotted for removal in 0.20 (Refer #841)
