### ISSUE TITLE
Implement Memory Pointers

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dpex#699]
Memory Pointers
EMM Plugins should construct memory pointer instances that represent their allocations, for return to Numba. The appropriate memory pointer class to use in each method is:

MemoryPointer: returned from memalloc

MappedMemory: returned from memhostalloc or mempin when the host memory is mapped into the device memory space.

PinnedMemory: return from memhostalloc or mempin when the host memory is not mapped into the device memory space.

**Comment by diptorupd** [comment]
Not relevant anymore. We now support USM allocators in NRT_Meminfo.
