### ISSUE TITLE
Rename `numba-dppy` to `numba-dpex`

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#723]
Python package and conda package name: `numba-dpex`
Python module name: `numba_dpex`
Product name: `Intel Data-parallel Extension for Numba`

- [x] Links to documentation
- [x] Links to GitHub repository
- [x] Links to coveralls.io project
- [x] Conda package name
- [x] Python package name
- [x] Python module name
- [x] Product name: `numba-dpex (f.k.a. numba-dppy)`
  - [x] Product name in README.md
- [x] Environment variables (e.g. `NUMBA_DPPY_*`)
- [x] Documentation
- [x] Import as `dppy`
- [x] `dppy` in names

Repositories:
- [x] GitHub
- [ ] coveralls.io

**Comment by diptorupd** [comment]
Done.
