### ISSUE TITLE
numba-dppy extension should have it's own CPU target

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dpex#74]
## Feature request

We should create our own target that inherits from the CPUTarget. We already have a dppl target but that target is specifically for the GPU code generation. This target will be the target that takes care of any CPU code we might need (like wrappers and calls made to the GPU code)

**Comment by reazulhoque** [comment]
Stand alone CPU target seems to fail as the process to register intrinsics and basic functions with this CPU target is not streamlined in Numba. One can create a separate CPU target but it seems to fail as a bunch of basic functions are undefined for this target.

**Comment by diptorupd** [comment]
Closing as recent changes to split up kernel target (`DpexKerneltarget`) and dpjit target (`DpexTarget`) mostly addresses the issue. The `DpexTarget` is not yet fully functional, possibly due to some Numba gaps.
