### ISSUE TITLE
Numba-dpex must resist the urge for hard pinning

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/numba-dpex#754]
This recipe is a masterpiece of obsessive version pinning.

https://github.com/IntelPython/numba-dpex/blob/main/conda-recipe/meta.yaml#L28

Such pinning is creating trouble for packages downstream. `dpctl` is using `numba-dpex` in its examples. 

As direct consequence of hard pinning the development version of `dpctl` (which is `0.13.0dev1`) can not be simultaneously installed with numba-dpex in the same environment causing build breakage.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk is this issue resolved with your latest changes?

**Comment by diptorupd** [comment]
Unfortunately, given the nature of fast changing depedencies and broken compiler builds I see no alternative to using hard pinning in the recipe.
