### ISSUE TITLE
SyclProgramCompilationError when running numba_dpex/examples/pairwise_distance.py 

### ISSUE THREAD

**Issue by ogrisel** [IntelPython/numba-dpex#756]
After installing dpctl and dpnp from the `dppy/label/dev` channel and the rest of their dependencies from the intel conda channel, I build the `main` branch of numba-dpex from source. But then I get the following error running the example.

```python-traceback
$ SYCL_DEVICE_FILER=level_zero python numba_dpex/examples/pairwise_distance.py
Using device ...
    Name            Intel(R) Iris(R) Xe Graphics [0x9a49]
    Driver version  1.3.23529
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   level_zero:gpu:0

Traceback (most recent call last):
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 109, in <module>
    main()
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 100, in main
    times = driver()
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 76, in driver
    pairwise_distance[global_size, local_size](
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 807, in __call__
    kernel = self.specialize(argtypes, compute_queue)
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 831, in specialize
    kernel = compile_kernel(
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 211, in compile_kernel
    oclkern = Kernel(
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 487, in __init__
    self.program = dpctl_prog.create_program_from_spirv(
  File "dpctl/program/_program.pyx", line 178, in dpctl.program._program.create_program_from_spirv
  File "dpctl/program/_program.pyx", line 209, in dpctl.program._program.create_program_from_spirv
dpctl.program._program.SyclProgramCompilationError
```

I also tried with `SYCL_DEVICE_FILER=opencl` and got the same exception. Only the device header changes to:

```
Using device ...
    Name            Intel(R) Iris(R) Xe Graphics [0x9a49]
    Driver version  1.3.23529
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   level_zero:gpu:0
```

Note that I had to add:

```
/opt/intel/oneapi/compiler/latest/linux/bin-llvm
```

to my PATH otherwise it would complain about not finding `llvm-spirv`. In this path, the `latest` part is a symlink to `2022.1.0` installed via the `intel-basekit` meta package for the Ubuntu distribution.

For reference:

```
$ python -c "import dpctl; dpctl.lsplatform()"
Intel(R) OpenCL HD Graphics OpenCL 3.0 
Intel(R) Level-Zero 1.3
SYCL host platform 1.2
```

I am running with `level-zero-devel 1.8.0` and `intel-level-zero-gpu 1.3.23529`.

**Comment by ogrisel** [comment]
Also, for some reason, I cannot access the OpenCL CPU device on this machine:

```
$ python -c "import dpctl; print(dpctl.get_devices())"
[<dpctl.SyclDevice [backend_type.opencl, device_type.gpu,  Intel(R) Iris(R) Xe Graphics [0x9a49]] at 0x7f2751c12370>, <dpctl.SyclDevice [backend_type.level_zero, device_type.gpu,  Intel(R) Iris(R) Xe Graphics [0x9a49]] at 0x7f2751c122f0>, <dpctl.SyclDevice [backend_type.host, device_type.host,  SYCL host device] at 0x7f2751c12330>]
```

**Comment by ogrisel** [comment]
More details on how I setup this environment:

https://github.com/ogrisel/sklearn-numba-dpex#step-1-a-conda-env-with-intel-python-libraries

**Comment by oleksandr-pavlyk** [comment]
> Also, for some reason, I cannot access the OpenCL CPU device on this machine:
> 
> ```
> $ python -c "import dpctl; print(dpctl.get_devices())"
> [<dpctl.SyclDevice [backend_type.opencl, device_type.gpu,  Intel(R) Iris(R) Xe Graphics [0x9a49]] at 0x7f2751c12370>, <dpctl.SyclDevice [backend_type.level_zero, device_type.gpu,  Intel(R) Iris(R) Xe Graphics [0x9a49]] at 0x7f2751c122f0>, <dpctl.SyclDevice [backend_type.host, device_type.host,  SYCL host device] at 0x7f2751c12330>]
> ```

The likely cause for this is that neither TBB component of oneAPI was not activated (only compiler), nor is TBB installed in conda-forge. 

If this is correct, doing either `conda install intel::tbb` or `source /opt/intel/oneapi/tbb/latest/env/vars.sh` should fix the issue and `sycl-ls` should start showing CPU device.

**Comment by ogrisel** [comment]
I did `conda install intel:tbb` in that environment and it installed it correctly. However I still get the same `SyclProgramCompilationError`.

```
$ sycl-ls
[opencl:gpu:0] Intel(R) OpenCL HD Graphics, Intel(R) Iris(R) Xe Graphics [0x9a49] 3.0 [22.25.23529]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Iris(R) Xe Graphics [0x9a49] 1.3 [1.3.23529]
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]
```

**Comment by ogrisel** [comment]
After sourcing the tbb env from the APT package I now get FPGA Emulation and OpenCL CPU devices:

```
$ source /opt/intel/oneapi/tbb/latest/env/vars.sh
$ sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.13.3.0.16_160000]
[opencl:cpu:1] Intel(R) OpenCL, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 3.0 [2022.13.3.0.16_160000]
[opencl:gpu:2] Intel(R) OpenCL HD Graphics, Intel(R) Iris(R) Xe Graphics [0x9a49] 3.0 [22.25.23529]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Iris(R) Xe Graphics [0x9a49] 1.3 [1.3.23529]
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]
```

However I still get the `SyclProgramCompilationError` when running the numba-dppex example.

**Comment by ogrisel** [comment]
I have tried again with `SYCL_DEVICE_FILTER=opencl:gpu python numba_dpex/examples/pairwise_distance.py` and I get the same exception than the one I get with the level zero gpu device.

When I run with `SYCL_DEVICE_FILTER=opencl:cpu` then the example works.

**Comment by ogrisel** [comment]
I tried on an other laptop with an older Iris Graphics 540 and the `pairwise_distance.py` code runs without crashing. On this machine I do not see the level zero device for the GPU, but the OpenCL device works.

**Comment by oleksandr-pavlyk** [comment]
The exception `SyclProgramCreationError` is raised when the SPIRV file generated by numba_dpex can be JIT-compiled to the binary form suitable for the GPU. 

The most likely explanation for the described behavior is that `numba_dpex` is generating code that uses doubles even though your input is a single precision array. 

Could you please try  `DPCTL_VERBOSITY=warning python numba_dpex/examples/pairwise_distance.py` to see the text of the exception raised by DPC++ runtime when trying to submit the kernel for execution?

I will try to set up access to Gen11 machine to be able to reproduce the issue as well.

**Comment by ogrisel** [comment]
Thanks, here is the output with the default device filter (level zero):

```
$ DPCTL_VERBOSITY=warning python numba_dpex/examples/pairwise_distance.py
Using device ...
    Name            Intel(R) Iris(R) Xe Graphics [0x9a49]
    Driver version  1.3.23529
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   level_zero:gpu:0

[ERR] No parent for device because it is not a subdevice -33 (CL_INVALID_DEVICE) in DPCTLDevice_GetParentDevice at /usr/share/miniconda/conda-bld/dpctl_1652840908396/work/libsyclinterface/source/dpctl_sycl_device_interface.cpp:540
[ERR] No parent for device because it is not a subdevice -33 (CL_INVALID_DEVICE) in DPCTLDevice_GetParentDevice at /usr/share/miniconda/conda-bld/dpctl_1652840908396/work/libsyclinterface/source/dpctl_sycl_device_interface.cpp:540
[WARN] ZeModule creation failed. in createLevelZeroInterOpProgram at /usr/share/miniconda/conda-bld/dpctl_1652840908396/work/libsyclinterface/source/dpctl_sycl_program_interface.cpp:188
Traceback (most recent call last):
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 109, in <module>
    main()
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 100, in main
    times = driver()
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 76, in driver
    pairwise_distance[global_size, local_size](
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 807, in __call__
    kernel = self.specialize(argtypes, compute_queue)
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 831, in specialize
    kernel = compile_kernel(
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 211, in compile_kernel
    oclkern = Kernel(
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 487, in __init__
    self.program = dpctl_prog.create_program_from_spirv(
  File "dpctl/program/_program.pyx", line 178, in dpctl.program._program.create_program_from_spirv
  File "dpctl/program/_program.pyx", line 209, in dpctl.program._program.create_program_from_spirv
dpctl.program._program.SyclProgramCompilationError
```

with OpenCL:

```
$ DPCTL_VERBOSITY=warning SYCL_DEVICE_FILTER=opencl python numba_dpex/examples/pairwise_distance.py
Using device ...
    Name            Intel(R) Iris(R) Xe Graphics [0x9a49]
    Driver version  22.25.23529
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   opencl:gpu:0

[ERR] No parent for device because it is not a subdevice -33 (CL_INVALID_DEVICE) in DPCTLDevice_GetParentDevice at /usr/share/miniconda/conda-bld/dpctl_1652840908396/work/libsyclinterface/source/dpctl_sycl_device_interface.cpp:540
[ERR] No parent for device because it is not a subdevice -33 (CL_INVALID_DEVICE) in DPCTLDevice_GetParentDevice at /usr/share/miniconda/conda-bld/dpctl_1652840908396/work/libsyclinterface/source/dpctl_sycl_device_interface.cpp:540
[WARN] OpenCL program could not be built. OpenCL Error -11. in createOpenCLInterOpProgram at /usr/share/miniconda/conda-bld/dpctl_1652840908396/work/libsyclinterface/source/dpctl_sycl_program_interface.cpp:114
Traceback (most recent call last):
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 109, in <module>
    main()
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 100, in main
    times = driver()
  File "/home/ogrisel/code/numba-dpex/numba_dpex/examples/pairwise_distance.py", line 76, in driver
    pairwise_distance[global_size, local_size](
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 807, in __call__
    kernel = self.specialize(argtypes, compute_queue)
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 831, in specialize
    kernel = compile_kernel(
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 211, in compile_kernel
    oclkern = Kernel(
  File "/home/ogrisel/code/numba-dpex/numba_dpex/compiler.py", line 487, in __init__
    self.program = dpctl_prog.create_program_from_spirv(
  File "dpctl/program/_program.pyx", line 178, in dpctl.program._program.create_program_from_spirv
  File "dpctl/program/_program.pyx", line 209, in dpctl.program._program.create_program_from_spirv
dpctl.program._program.SyclProgramCompilationError
```

**Comment by oleksandr-pavlyk** [comment]
No parent for device exception is expected. It arises while calling `dev.parent`, and is translated into `None` return.

The OpenCL backend reports code -11, [corresponding](https://streamhpc.com/blog/2013-04-28/opencl-error-codes/) to `CL_BUILD_PROGRAM _FAILURE`.

To understand the reason for the failure requires extracting the SPIRV binary `numba_dpex` generated.

I will look at this in more details next week after returning to the office.

**Comment by ogrisel** [comment]
> Numba-dpex currently has a defect that is causing compilation failure when executed on GPUs with multiple stacks.

Is there an open issue to link so as to track the resolution of this problem and maybe get a bit more details?

**Comment by oleksandr-pavlyk** [comment]
@ogrisel I was able to reproduce the issue. The issue is due to use of Python constant `0.0` to initialize the distance `d`. Since the Python scalar is of double precision by default, type inference deduces that `d` is a double precision variable. 

The fix could be as in 

https://github.com/IntelPython/numba-dpex/blob/fix-pairwise-distance-for-single-precision/numba_dpex/examples/pairwise_distance.py

**Comment by ogrisel** [comment]
Thanks, i confirm that wrapping the 0.0 scalar with numba.float32(0.0) fixes the compilation problem on my iris card.

**Comment by ogrisel** [comment]
Now that we understand the problem, let me close this issue and open another one more explicitly dedicated to improve the error message.
