### ISSUE TITLE
segfault when running numba_dpex/examples/pairwise_distance.py on 

### ISSUE THREAD

**Issue by fcharras** [IntelPython/numba-dpex#758]
I've installed and started numba-dpex and the environment with instructions seen in [this dockerfile](https://github.com/ogrisel/sklearn-numba-dpex/blob/bc881f7417f423b539f14c664f52c8674bfbf28a/docker/Dockerfile).

I get the following segfault running the pairwise_distance.py:
```
root@49272d101c13:~# python -m numba_dppy.examples.pairwise_distance
Using device ...
    Name            Intel(R) HD Graphics 505 [0x5a84]
    Driver version  22.26.23599
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   opencl:gpu:0

Segmentation fault (core dumped)
```
The gdb output from running `gdb --ex run --ex backtrace --args python -m numba_dppy.examples.pairwise_distance`:

~~[gdb.txt](https://github.com/IntelPython/numba-dpex/files/9095106/gdb.txt)~~ [gdb.txt](https://github.com/IntelPython/numba-dpex/files/9100852/gdb.txt)

The same example runs successfully on cpu:
```
root@49272d101c13:~# SYCL_DEVICE_FILTER=cpu python -m numba_dppy.examples.pairwise_distance
Using device ...
    Name            Intel(R) Pentium(R) CPU N4200 @ 1.10GHz
    Driver version  2022.13.3.0.16_160000
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   opencl:cpu:0

Average time of 1 runs is = 2.296651s
Done...
```

Also:
```
root@49272d101c13:~# python -c "import dpctl; dpctl.lsplatform()"
Intel(R) OpenCL OpenCL 3.0 LINUX
Intel(R) OpenCL HD Graphics OpenCL 3.0 
Intel(R) FPGA Emulation Platform for OpenCL(TM) OpenCL 1.2 Intel(R) FPGA SDK for OpenCL(TM), Version 20.3
Intel(R) OpenCL OpenCL 3.0 LINUX
SYCL host platform 1.2
```

**Comment by fcharras** [comment]
Device: 

`00:02.0 VGA compatible controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Integrated Graphics Controller (rev 0b)`

driver: `i915`

**Comment by ogrisel** [comment]
Is the output:

```python-traceback
Traceback (most recent call first):
  <built-in method copyto of module object at remote 0x7ffff17a2630>
  <built-in method implement_array_function of module object at remote 0x7ffff17a2630>
  File "<__array_function__ internals>", line 180, in copyto
  File "/opt/venv/lib/python3.9/site-packages/numba_dppy/examples/pairwise_distance.py", line 68, in driver
    np.copyto(x_ndarray, X)
  File "/opt/venv/lib/python3.9/site-packages/numba_dppy/examples/pairwise_distance.py", line 100, in main
    times = driver()
  File "/opt/venv/lib/python3.9/site-packages/numba_dppy/examples/pairwise_distance.py", line 109, in <module>
    main()
  <built-in method exec of module object at remote 0x7ffff7827860>
  File "/opt/pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
Python Exception <class 'UnicodeDecodeError'> 'ascii' codec can't decode byte 0xe2 in position 81: ordinal not in range(128): 
Error occurred in Python: 'ascii' codec can't decode byte 0xe2 in position 81: ordinal not in range(128)
```
the result of running `py-bt`?

**Comment by fcharras** [comment]
Yes

**Comment by ogrisel** [comment]
For quick access here are the first line of the native backtrace:

```
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:468
#1  0x00007ffff06ea762 in _contig_to_contig ()
   from /opt/venv/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
#2  0x00007ffff0668eeb in raw_array_assign_array ()
   from /opt/venv/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
#3  0x00007ffff06697c8 in PyArray_AssignArray ()
   from /opt/venv/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
#4  0x00007ffff0728004 in array_copyto ()
   from /opt/venv/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
```

So the `np.copyto` is triggering a `__memmove_sse2_unaligned_erms` that fails. However I fail to understand how this relates to the final message of the Python traceback: `Error occurred in Python: 'ascii' codec can't decode byte 0xe2 in position 81: ordinal not in range(128)`...

**Comment by oleksandr-pavlyk** [comment]
@fcharras The issue is likely that the binary of the NumPy itself was compiled instruction sets of more recent architecture. If NumPy from Intel Distribution for Python was used, it requires CPUs capable of SSE4_2 ISA extension or higher. 

I am not sure whether the 'ascii' codec error is related the crash or not, but I am inclined to think it is not related.

**Comment by fcharras** [comment]
@oleksandr-pavlyk thank you for your explanations. I will use more recent hardware for the time being.

**Comment by fcharras** [comment]
Could be closed if it only impact very old CPUs.

**Comment by oleksandr-pavlyk** [comment]
@mingjie-intel @diptorupd Is this ticker worth keeping open?

**Comment by diptorupd** [comment]
Let us close.
