### ISSUE TITLE
`numba_dpex` is not pip installable

### ISSUE THREAD

**Issue by fcharras** [IntelPython/numba-dpex#775]
Users of software built on `numba_dpex` will expect `numba_dpex` to be easily installable (like it is with other stacks like e.g `pytorch` is) or will refrain to adopt it, and one of the common way to install python stack is using `pip install`, but at the moment `numba_dpex` is not easily pip-installable. In fact the `numba_dpex` wheel is not pushed to `pypi`:

```
$ pip install numba-dpex
ERROR: Could not find a version that satisfies the requirement numba_dpex (from versions: none)
ERROR: No matching distribution found for numba_dpex
```

so to install `numba_dpex` outside of a conda environment one needs to build from source.

I've listed the steps to install the `numba_dpex` stack without conda and using pip in [this Dockerfile](https://github.com/soda-inria/sklearn-numba-dpex/blob/main/docker/Dockerfile) and beside the lack of `numba_dpex` wheel in `pypi`, here are the few other issues that will prevent single-step pip installation:

- `dpctl` and `dpnp` exist on `pypi.org` but are not up to date 

- `numba_dpex` requires the dpcpp runtime to work, the dpcpp runtime is already available in a python package `dpcpp_cpp_rt` but this package is not listed in the dependencies of `numba_dpex` or `dpctl`. `dpcpp_cpp_rt` should be listed as a requirement in `numba_dpex`

- the runtime also requires the `llvm-spirv` binary to figure in the `$PATH`, so far the `llvm_spirv` binary is not distributed as a python wheel, one must install the oneapi intel basekit to obtain the binary. A python wheel containing the `llvm_spirv` binary in the dependency tree of `numba_dpex` is necessary for single-step pip installation.

- some environment variables must be manually tweaked ( [ `LD_LIBARY_PATH`](https://intelpython.github.io/dpctl/latest/docfiles/user_guides/QuickStart.html#install-wheel-package-from-pypi), [`OCL_ICD_FILENAMES_RESET` and `OCL_ICD_FILENAMES`](https://github.com/IntelPython/dpnp/#install-wheel-package-from-pypi) (if using dpnp) ), having to manually set environment variables is unusual in the python ecosystem, having to manage custom environments will cause friction to adoption

- it is not clear if `dpnp` is required or not and the list of features it unlocks ? (`dpnp` is not an `install_require` nor a `setup_requires` or an `extras_require`, but the build fails if `dpnp` is not importable, except if `NUMBA_DPEX_BUILD_SKIP_NO_DPNP` is set to 1.) 

- are intel numpy / intel scipy mandatory to unlock `numba_dpex` or `dpnp` features ?

- I figured that the python package `mkl-dpcpp` is also required but is not included in the dependency tree (but I can't reproduce issues if the packages is missing). It might just be an intel numpy issue (because it is not in the dependency tree of intel numpy either)

- i've found that `spirv-tools` and `spirv-headers` still need to be installed independantly, could it be on pypi.org too as wheels and listed as dependencies of `numba_dpex`?

- Except for the kernel drivers, the low level backends `opencl` and `level_zero` maybe could also be provided in python wheels and added as dependencies of `numba_dpex`, e.g in the same way [pyopencl bundles libraries](https://documen.tician.de/pyopencl/misc.html#installing-from-pypi-wheels) ? 

In fact we're not too far from being fully single-step pip-installable as those issues seems each reasonable to solve ? if you prefer I could also split this list into several issues, some of them in upstream packages (for dpnp, dpctl. spirv, etc ?)

**Comment by xaleryb** [comment]
Hello @fcharras. 
First of all I want to say sorry for delay with response. 
After checking this issue I can say all comments and concernse  are correct and definitely need to be resolved.
The main problem which is caused almost all problems you described is that we temporary stopped PyPi releases support due to internal problems. Good news here is that we are working on it right now and expecting some results at 2H of 2023.
Per my expectation improved CI/CD process for wheels packages will cover problems described above. 
When it will be implemented we can work closely to improve process in details to cover everything.

**Comment by diptorupd** [comment]
Latest numba-dpex package along with all dependencies is now installable using `pip`. https://pypi.org/project/numba-dpex/
