### ISSUE TITLE
Improvements to atomic operations in numba-dpex kernels

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#783]
This is a meta ticket to track issues and improvements to the atomic operations supported by numba-dpex:

- [x] Reevaluate the need for the emulated atomics with latest dpcpp runtimes.
- [x] The emulated atomics implementation is linked to the main spv module using `spirv-link`. `spirv-link` is deprecated and if the emulated atomics function is to be retained, it should be linked using `llvm-link`.
- [x] Fix #650 that relates directly to the use of spirv-link.
- [x] Evaluation of dpex using the dpbench benchmark suite showed atomics generating incorrect results on CPUs https://github.com/IntelPython/dpbench/issues/127. Also reported in #711
- [x] https://github.com/IntelPython/numba-dpex/issues/161 (Feature request)
- [x] The generation of atomic code should be based on the device capabilities that can be looked up using SYCL device info.
- [x] The documentation of dpex's atomics support has to be improved.
- [ ] Look at numba.cuda.cudadecl and incorporate a similar design for dpex atomic intrinsics

**Comment by adarshyoga** [comment]
Reevaluate employing environment variables (NUMBA_DPEX_ACTIVATE_ATOMICS_FP_NATIVE, NUMBA_DPEX_LLVM_SPIRV_ROOT) to enable native atomics. Ideally, numba-dpex should be able to query if a system supports native atomics and should automatically use the available `llvm_spirv` without requiring the user to manually specify the path through environment variables.

**Comment by adarshyoga** [comment]
Two additional design points to be aware of while developing atomics.
1) Currently `AtomicRef` in numba-dpex can be allocated only on USMNDArray objects which are allocated in global memory. In addition to global memory, numba-dpex should also be capable of creating an AtomicRef out of a local memory (or a private memory?) object.
2) `MemoryScope` argument to `AtomicRef` should be adjusted appropriately based on the associated memory location. For example, if MemoryScope is set to `device`, but the associated memory location is in SLM, SYCL specifies that `MemoryScope` is adjusted to a narrower scope, which is `work_group` in this example.
For detailed explaination refer to the [SYCL spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_memory_scope).

**Comment by diptorupd** [comment]
The atomic operations for numba-dpex kernels has been completely redesigned and implemented using a new SYCL-like `AtomicRef` class. API docs are also available on the documentation page.
