### ISSUE TITLE
Turn parfor fallbabk to CPU off by default

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#793]
The automatic fallback feature in dpex leads to confusing behavior for users who may not be properly notified when a parfor was not offloaded and instead ran on the CPU.

The issue suggests the following changes in dpex's parfor fallback feature:

- [ ] Fallback should be turned off by default and users can opt in if the want.
- [ ] If a parfor node fails to be offloaded, then the error message can advise users to turn on fallback if they want.
- [ ] Any time fallback is used, a warning should be printed out to notify users.
- [ ] Unit test cases that check fallback functionally should be properly updated.

**Comment by chudur-budur** [comment]
@diptorupd

**Comment by adarshyoga** [comment]
Automatic fallback to numba seems to be still occurring in certain cases. @ZzEeKkAa had to explicitly set `NUMBA_DPEX_FALLBACK_ON_CPU=0` to prevent knn's failing prange from silently falling back to numba on CPU and executing successfully.

**Comment by diptorupd** [comment]
Fallback and the deprecated `lowerer` are now removed in main.
