### ISSUE TITLE
Blackscholes GPU version performs 42X more FLOPs than CPU version

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#81]
The roofline performance graphs show that the GPU execution has a performance of 217.8 GFLOPS and the CPU execution has a performance of 7.3 GFLOPS. In spite for higher performance on GPU, computation time is almost the same on CPU and GPU. This indicates that the GPU execution is performing a large number of floating-point operations (FLOPs) compared to the CPU execution.
Using Intel Advisor we found that the GPU execution is performing 42.2X more FLOPs that the CPU execution (376.179 GFLOPs GPU vs 8.89612 GFLOPs CPU). This is likely due to a performance gap in the code generation in Numba.

We need to find the cause for large FLOPs generated by Numba on GPU.

**Comment by diptorupd** [comment]
@adarshyoga I believe it is no longer an issue. Please reopen if you see any performance regressions.
