### ISSUE TITLE
CompileResult object in SpirvKernel doesn't have codegen attribute

### ISSUE THREAD

**Issue by chudur-budur** [IntelPython/numba-dpex#819]
At [line 97](https://github.com/IntelPython/numba-dpex/blob/refactor/kernel_interfaces/numba_dpex/core/kernel_interface/spirv_kernel.py#L97) in `SprivKernel`,  The `CompileResult` object `cres` supposed to have [`SPIRVCodeLibrary`](https://github.com/IntelPython/numba-dpex/blob/refactor/kernel_interfaces/numba_dpex/codegen.py#L26) in its `codegen` attribute. 

But if you probe by calling `print(cres.codegen)`, it says `AttributeError: 'CompileResult' object has no attribute 'codegen'`.

However in every occurrence of `CompileResult` in `numba`, the `codegen` attribute is always populated with appropriate `CodeLibrary`, like [`CPUCodeLibrary`](https://github.com/numba/numba/blob/release0.55/numba/core/codegen.py#L642) or [`JITCodeLibrary`](https://github.com/numba/numba/blob/release0.55/numba/core/codegen.py#L974).

This needs to be fixed.

**Comment by diptorupd** [comment]
@chudur-budur is the issue still relevant?

**Comment by chudur-budur** [comment]
> @chudur-budur is the issue still relevant?

No, it's been resolved.
