### ISSUE TITLE
Support "with device context" within jit-compiled region

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#83]
Currently Numba does not allow calls to "with dpctl.device_context("opencl:gpu"):" from inside jit-compiled functions. This inhibits a section of code inside a deep call chain from being executed on the GPU.
Consider for example:
```
@numba.jit(nopython=True, parallel=True, fastmath=True)
def get_neighbors(x_train, labels, x_test, k=5):
    for i in numba.prange(len(x_train)):
         ....

@numba.jit(nopython=True)
def run_knn(x_train, y_train, test, k=5, classes_num=3):
    test_size = len(test)
    predictions = np.empty(test_size)

    for i in range(test_size):
        neighbors = get_neighbors(x_train, y_train, test[i], k)
```

To offload get_neighbors function to the GPU, we need to call run_knn from inside a dpctl device context like this:
```
with dpctl.device_context("opencl:gpu"):
   run_knn(x_train, y_train, test, k, classes_num)
```

Ideally, only the call to get_neighbors needs to be from a dpctl device context, not the entire run_knn function.
To achieve this, ideally, we need to be able to support calls to "with dpctl.device_context("opencl:gpu"):" from inside jit-compiled functions.

**Comment by diptorupd** [comment]
`device_context` is deprecated and is being replaced with compute follows data programing model.
