### ISSUE TITLE
Consistent import numba vs. numba_dpex

### ISSUE THREAD

**Issue by samaid** [IntelPython/numba-dpex#847]
The usage model needs to be consistent. Earlier the approach was to import numba and enable numba_dpex if inputs are usm ndarray.

Lately we revised the approach, and enable numba_dpex explicitly via import. By going this route, the implementation is numba_dpex need to be self-contained, and alias necessary attributes from numba.

The goal is to have a model that minimizes code changes by going from CPU script to heterogeneous script. It means in particular that we have to avoid situations when user needs to import both numba and numba_dpex.

Examples of aliases needed in numba_dpex
- [x] primitive types - float32, int64, etc (#830)
- [ ] vectorize
- [X] njit (#887)

**Comment by diptorupd** [comment]
`vectorize` decorator has been removed and no longer supported (refer #1298, #1299). The rest of the decorators are ported to numba_dpex namespace.
