### ISSUE TITLE
dpex failed to call dpnp.ones_like()

### ISSUE THREAD

**Issue by mingjie-intel** [IntelPython/numba-dpex#857]
Currently, 4 tests failed in dpex. They are due to failed to call dpnp.ones_like():
Failed tests:
numba_dpex/tests/integration/test_dpnp_interop.py::test_consuming_array_from_dpnp

A reproducer is here:

```
import dpctl
import numpy as np
import dpnp

import numba_dpex as dpex

dtype=np.int32

@dpex.kernel
def data_parallel_sum(a, b, c):
        """
        Vector addition using the ``kernel`` decorator.
        """
        i = dpex.get_global_id(0)
        c[i] = a[i] + b[i]

global_size = 1021

with dpctl.device_context("level_zero:gpu:0"):
        a = dpex.asarray(dpnp.arange(global_size, dtype=dtype))
        b = dpex.asarray(dpnp.arange(global_size, dtype=dtype))
        c = dpex.asarray(dpnp.ones_like(a))
data_parallel_sum[global_size, dpex.DEFAULT_LOCAL_SIZE](a, b, c)
```

**Comment by diptorupd** [comment]
Fixed in #880. A change in the behavior of `dpnp.ones_like` means that `dpctl.asarray` is no longer able to convert the dpnp output to a usm_ndarray.

The test case needs to be updated to latest API of dpnp, dpctl and numba_dpex. The fix in #880 updates the test case.
