### ISSUE TITLE
Unstability after bumps to 2023 oneapi releases (with minimal reproducer)

### ISSUE THREAD

**Issue by fcharras** [IntelPython/numba-dpex#865]
After bumping to the 2023 oneapi releases, and latest `dpctl` and `numba_dpex` latest commits that should be compatible, I see occurences of surprising kernel failures.

Here's a minimal reproducer, that runs just fine with latest 2022 oneapi releases, but fails with 2023 oneapi release:

```python
import math
from functools import lru_cache

import dpctl
import dpctl.tensor as dpt
import numba_dpex as dpex
import numpy as np


@lru_cache
def make_initialize_to_zeros_1d_kernel(size, work_group_size, dtype):
    global_size = math.ceil(size / work_group_size) * work_group_size
    zero_idx = np.int64(0)
    zero = dtype(0.0)

    @dpex.func
    def set_to_zero(array, idx):
        array[idx] = zero

    @dpex.kernel
    def initialize_to_zeros(data):
        item_idx = dpex.get_global_id(zero_idx)
        local_item_idx = dpex.get_local_id(zero_idx)

        some_shm = dpex.local.array(shape=work_group_size, dtype=dtype)
        set_to_zero(some_shm, local_item_idx)  # fails
        # some_shm[local_item_idx] = zero      # works

        if item_idx >= size:
            return

        data[item_idx] = zero

    return initialize_to_zeros[global_size, work_group_size]


dtype = np.float64  # fails
# dtype = np.float32  # works

device = dpctl.SyclDevice("cpu")
size = 2
work_group_size = device.max_work_group_size  # fails
# work_group_size = 4096  # works

array_ones = dpt.ones(sh=(size,), device=device, dtype=dtype)

initialize_to_zeros_kernel = make_initialize_to_zeros_1d_kernel(
    size, work_group_size, dtype
)

initialize_to_zeros_kernel(array_ones)
```

It fails with the following error in an environment with 2023 oneapi releases:

```
File dpctl/_sycl_queue.pyx:714, in dpctl._sycl_queue.SyclQueue.submit()

File dpctl/_sycl_queue.pyx:831, in dpctl._sycl_queue.SyclQueue.submit()

SyclKernelSubmitError: Kernel submission to Sycl queue failed.
```

But:

- it runs fine with latest 2022 oneapi releases
- replace any of the line tagged with `fail` with the next line tagged with `works` and the kernel will run fine. In particular I find surprising that the same code that works without factoring in a kernel func, fails if a single line is factored in a kernel func.

I wonder if someone could try to reproduce this behavior on different hardware or other environments and confirm that it is a bug introduced by bumps to 2023 releases ?

@oleksandr-pavlyk maybe this could be related to `dpctl` or in 2023 `dpcpp` at a lower level rather than `numba_dpex` ?

**Comment by oleksandr-pavlyk** [comment]
@fcharras I can replicate this issue as well.

```bash
(dppy_stack2) opavlyk@opavlyk-mobl:~$ OCL_ICD_FILENAMES=libintelocl.so python issue_865.py
/home/opavlyk/miniconda3/envs/dppy_stack2/lib/python3.9/site-packages/llvmlite/llvmpy/__init__.py:3: UserWarning: The module `llvmlite.llvmpy` is deprecated and will be removed in the future.
  warnings.warn(
/home/opavlyk/miniconda3/envs/dppy_stack2/lib/python3.9/site-packages/llvmlite/llvmpy/core.py:8: UserWarning: The module `llvmlite.llvmpy.core` is deprecated and will be removed in the future. Equivalent functionality is provided by `llvmlite.ir`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/opavlyk/issue_865.py", line 51, in <module>
    initialize_to_zeros_kernel(array_ones)
  File "/home/opavlyk/miniconda3/envs/dppy_stack2/lib/python3.9/site-packages/numba_dpex/compiler.py", line 809, in __call__
    cfg(*args)
  File "/home/opavlyk/miniconda3/envs/dppy_stack2/lib/python3.9/site-packages/numba_dpex/compiler.py", line 513, in __call__
    self.sycl_queue.submit(
  File "dpctl/_sycl_queue.pyx", line 714, in dpctl._sycl_queue.SyclQueue.submit
  File "dpctl/_sycl_queue.pyx", line 831, in dpctl._sycl_queue.SyclQueue.submit
dpctl._sycl_queue.SyclKernelSubmitError: Kernel submission to Sycl queue failed.
(dppy_stack2) opavlyk@opavlyk-mobl:~$
```

Thank for the reproducer!

**Comment by oleksandr-pavlyk** [comment]
The kernel uses SLM, and submission will fail if kernel uses more SLM that device can provide. 

```
In [2]: dev = dpctl.SyclDevice("cpu")

In [3]: dev.local_mem_size
Out[3]: 32768

In [4]: dev.max_work_group_size
Out[4]: 8192

In [5]: dev.max_work_group_size * 8
Out[5]: 65536

In [6]: dev.max_work_group_size * 4
Out[6]: 32768
```

This explains why it works with `device.max_work_group_size` and `float32`, and with `work_group_size=4096` and `float64`. 

I do not have an immediate explanation for why doing `some_shm[local_item_idx] = zero` works, but calling a function does not. Perhaps IGC is able to deduce that local array goes unused when direct assignment is used, and simply optimizes it out.

**Comment by fcharras** [comment]
TY for the feedback! 

But also, with the oneapi 2022 the kernel func version seems to run fine. That is inconvenient because the bump to 2023 breaks some of my code where I mindlessly set work group size to max_work_group_size on cpus.

So it would be one of those two explanations:

- 2022 releases used to run even wirh overflowed SLM but with an undefined behavior (which I think I have indeed noticed before, but the unit tests that 2023 broke in my pipeline never failed, didn't look like it was really undefined behavior there), and that would have changed in 2023 releases

- or 2023 releases cause more SLM use than before. Maybe there could still be a bug there ?

**Comment by fcharras** [comment]
> Perhaps IGC is able to deduce that local array goes unused when direct assignment is used, and simply optimizes it out.

In this case that seems to explain, by making sure that the shared memory is used it fails in both cases:

```
@lru_cache
def make_initialize_to_zeros_1d_kernel(size, work_group_size, dtype):
    global_size = math.ceil(size / work_group_size) * work_group_size
    zero_idx = np.int64(0)

    @dpex.func
    def set_to_idx(array, idx):
        array[idx] = idx

    @dpex.kernel
    def initialize_to_zeros(data):
        item_idx = dpex.get_global_id(zero_idx)
        local_item_idx = dpex.get_local_id(zero_idx)

        some_shm = dpex.local.array(shape=work_group_size, dtype=dtype)
        # set_to_idx(some_shm, local_item_idx)  # fails
        some_shm[local_item_idx] = local_item_idx      # fails

        dpex.barrier(dpex.CLK_LOCAL_MEM_FENCE)

        if item_idx >= size:
            return

        data[item_idx] = some_shm[(item_idx + 1) % work_group_size]

    return initialize_to_zeros[global_size, work_group_size]
```

but still works with oneapi 2022.

**Comment by diptorupd** [comment]
I want to investigate the behaviour and see if we can do confirm the root cause and do something to improve the UX. Reopening the ticket open to not forget about it.

**Comment by diptorupd** [comment]
The SLM feature has been redesigned using the new `numba_dpex.kernel_api.LocalAccessor` class. In the new design, SLM allocation now happens outside the kernel and should make it easier to check SLM allocation size prior to submitting kernels.
