### ISSUE TITLE
The `numba_dpex==0.19.0` build on conda channel `dppy/label/dev` is built with a commit posterior to `0.19.0`

### ISSUE THREAD

**Issue by fcharras** [IntelPython/numba-dpex#870]
Several differences between `0.19.0` tag on the repository and the build on the conda channel `dppy/label/dev`:

- `CLK_LOCAL_MEM_FENCE` has been renamed `LOCAL_MEM_FENCE`
- the behavior of caching has changed again (seems there's no caching at all anymore - even a kernel call with a `pyfunc` that has the same `id(func)` and the same signature seems to not cache anymore ?)

Would it be possible to make it so the default `numba_dpex` build resolved by `conda` is a built from the `0.19.0` tag in the repository ?

**Comment by ogrisel** [comment]
I have the feeling that this is expected. The package found in `dppy/label/dev` reflect the current state of the `main` branch of the git repo, not the git tag `0.19.0`.

The build number returned by "mamba list numba_dpex" has a `_21` suffix which matches the version found in the source tree when doing:

```python
cd numba_dpex
python
>>> import _version
>>> _version.get_versions()['version']
'0.19.0+21.ga541db59'
```

If you want to install the real `0.19.0` version, do not use the `dppy/label/dev` channel but the `intel` channel instead.

**Comment by ogrisel** [comment]
But to avoid any confusion, it would be best to bump the version number of `main` to `0.20.0` in anticipation of the next release.

**Comment by fcharras** [comment]
I see. I'll just pin the build then. (I prefer continuing using `numba-dpex` from `dppy/label/dev` channel rather than `intel` since we're still all moving fast - however, it would be nice if we can start thinking of stabilizing the interfaces in the perspective of a release schedule)

**Comment by ogrisel** [comment]
Still I think it would be good practice to change the version number of the `main` development branch to target the next release version (with the `.dev`) suffix to avoid confusion.
