### ISSUE TITLE
Perormance regressions introduced by latest changes to main

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#886]
> I also see segfaults, makes me think that something is wrong with local memory.

_Originally posted by @fcharras in https://github.com/IntelPython/numba-dpex/issues/816#issuecomment-1400514147_

> The new problems are not related to #877 but to #876 , reported in https://github.com/IntelPython/numba-dpex/issues/816

_Originally posted by @fcharras in https://github.com/IntelPython/numba-dpex/issues/867#issuecomment-1400406083_

**Comment by fcharras** [comment]
@diptorupd @chudur-budur

We're having conversations about this in multiple separate issues, let's keep it in this dedicated thread ?

> > I also see segfaults, makes me think that something is wrong with local memory.
> 
> The problem most likely is because I without realizing the impact changed the way the global and local range args passed to the `__getitem__`. We are working on reverting my changes and fixing the issue.

Do you still need a minimal reproducer ? I haven't come up with one yet. Yet again it's not trivial to reproduce, simple kernels still work.

If you have a commit that revert those changes I can easily say if it fixes the issues though. (basically running the benchmark script in https://github.com/soda-inria/sklearn-numba-dpex )

**Comment by diptorupd** [comment]
@fcharras No we do not need th reproducer. Let @chudur-budur open the PR and then you can test and let us know if the issue is fixed.

**Comment by chudur-budur** [comment]
@fcharras Could you please test PR #888 and check if you are seeing any performance issues?

**Comment by fcharras** [comment]
Unfortunately, issues persists in #888 :-(

I just realized that I made a mistake in my bug report that might have misled you. The problems start at the merge commit of https://github.com/IntelPython/numba-dpex/pull/804 not https://github.com/IntelPython/numba-dpex/pull/876 . The merge commits of those two PRs are very close to each other and I missclicked the copy/paste :-/

**Comment by chudur-budur** [comment]
@fcharras Could please test #896 and see if you are getting any slowdown?

**Comment by fcharras** [comment]
@chudur-budur @diptorupd please see https://github.com/IntelPython/numba-dpex/issues/898 that give a minimal reproducer for what caused the regression I was facing, which is more than a performance issue.

However, it appears fixing it will not be the end. After understanding the bug I could test the `KMeans` in a way that doesn't trigger it (changing some parameters), and I still see a minor slow down. I think the refacto also added some python overhead. But, that should be easier to debug with normal profiling ? maybe the cache keys that are computed are a bit too computationally heavy. There are probably several expensive calls that can be saved. (no need to re-hash the codegen every time for instance)

But~ there are two more important issues to solve first IMO.

**Comment by diptorupd** [comment]
Closing the issue as the caching related performance regressions have been addressed and the code generation issue in #898 is solved.
