### ISSUE TITLE
Add boxing and unboxing functions for dpnp.ndarray to numba_dpex

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#890]
To support `dpnp.ndarray` as input args to numba-dpex's version of `njit` decorator, numba-dpex should be able to convert a `dpnp.ndarray` PyObject to a native Numba representation and _vice-versa_ at function boundaries.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I have made some progress on the boxing and unboxing support for `dpnp.ndarray`. The latest version of the WIP code is in : https://github.com/IntelPython/numba-dpex/blob/dpnp_ndarray_update_v3/numba_dpex/core/types/dpnp_ndarray_type.py.

I am considering switching to dpctl_capi.h to not have to reinvent the getter functions for unboxing a `dpnp.ndarray`. Before I make any changes here are few questions:

1. Will the getters defined in `_usmarray_api.h` work on a `PyObject` of type `dpnp.ndarray`?
2. I do not see any setters or constructors for `UsmNDArray` in the CAPI. To return a `dpnp.ndarray` (boxing) from an `njit` function should I create a `PyUSMArrayObject` object directly and then set the needed attributes?
3. If 2) above is a correct assumption, how do I use the object to create a `dpnp.ndarray` from the C API? I was thinking of calling the interpreter and somehow call the `dpnp.ndarray` constructor and pass in the `PyUSMArrayObject` and return that `PyObject`.

Advise will be much appreciated.

**Comment by oleksandr-pavlyk** [comment]
You are right, there are no constructors in `_usmarray_api.h`, only getters at the moment, and these expect `PyUSMArrayObejct`. 

At the moment, the recommended way to create `usm_ndarray` is to use C-API `Memory_Make` to create memory object `mobj` from existing USM allocation, and then call Python interpreter to execute `usm_ndarray(shape, dtype=dtype, buffer=mobj)`.

I will add  `UsmNDArray_Make(int nd, ssize_t *shape, int typenum, c_dpctl.memory._Memory mobj)` to dpctl's C-API to eliminate the need to call the interpreter and the need to create shape tuple.

**Comment by diptorupd** [comment]
Completed in #902
