### ISSUE TITLE
Minimal reproducer for regression in #804

### ISSUE THREAD

**Issue by fcharras** [IntelPython/numba-dpex#898]
Performances issues #804 have been reported in https://github.com/IntelPython/numba-dpex/issues/891 and https://github.com/IntelPython/numba-dpex/issues/886

In fact, what I have reported as a performance issue is really a JIT issue, maybe related to caching.  Sorry for misleading you into thinking that might be only related to performance. The way it surfaced on the benchmarks was a general slowdown on GPU because rather than segfaulting it returns corrupted results that trigger a slower code branch in our KMeans (cluster relocation). On CPU it gives segfaults, meaning the wrong code was executed, so I could have thought sooner about errors in the compiled code.

I think it might be related to caching, but I have looked for the error in the python depth of `numba_dpex` (post- #804 ) without any luck, the bug must be well hidden.

I finally came up with a minimal reproducer of what cause the regression in my code:

```python
import numba_dpex as dpex
import dpctl.tensor as dpt


def make_write_values_kernel(n_rows):

    write_values = make_write_values_kernel_func()

    @dpex.kernel
    def write_values_kernel(array_in):
        for row_idx in range(n_rows):
            is_even = (row_idx % 2) == 0
            write_values(array_in, row_idx, is_even)

    return write_values_kernel[1, 1]


def make_write_values_kernel_func():
    write_when_even = _make_write_values_kernel_func(4)
    write_when_odd = _make_write_values_kernel_func(2)

    @dpex.func
    def write_values(array_in, row_idx, is_even):
        if is_even:
            write_when_even(array_in, row_idx)
        else:
            write_when_odd(array_in, row_idx)

    return write_values


def _make_write_values_kernel_func(n_cols):
    @dpex.func
    def write_values(array_in, row_idx):
        for idx in range(n_cols):
            array_in[row_idx, idx] = 1

    return write_values


kernel = make_write_values_kernel(10)
array_in = dpt.empty(sh=(10, 10), dtype=dpt.int64)
kernel(array_in)
print(array_in)
```

Read it attentively, it should output the following:
```
[[1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]]
```

but instead the output is:

```
[[1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]]
```

(basically, when `write_when_odd` should be called,  it's `write_when_even` that is called instead, since those two funcs have the same code and the same name it suggests a caching issue)

Important notes:

- it works with `numba_dpex == 0.19.0` when using this patch that we apply by monkey-patching in `numba_dpex`: https://github.com/soda-inria/sklearn-numba-dpex/blob/main/sklearn_numba_dpex/patches/load_numba_dpex.py#L45
- it (probably - haven't tested this specific case but our `KMeans` didn't have issues then) works with `numba_dpex < 0.19.0`

In case you wonder why one would come up with such convoluted cascade of `dpex.func`s: basically in `sklearn_numba_dpex` we factor some code using `dpex.func` kernel functions that are defined as closures and re-instantiated with different parameters every time it's needed. See https://github.com/soda-inria/sklearn-numba-dpex/blob/main/sklearn_numba_dpex/kmeans/kernels/_base_kmeans_kernel_funcs.py . This is the best solution for factoring redundant code that I've thought of (and it only works as long as there are no local memory allocation or barriers in the factored code) ).

Note that https://github.com/IntelPython/numba-dpex/issues/892 doesn't seem to be related at all, since it's already wrong for `numba_dpex == 0.19.0`.

**Comment by chudur-budur** [comment]
You can disable caching with `NUMBA_DPEX_ENABLE_CACHE=0 python <code>`. I did a quick check by disabling the cache and the results are still wrong (all rows 4 zeros). Which means the bug is not coming from the caching mechanism. 

Looks like the issue is with `@func` decorator. We are looking into it.

**Comment by diptorupd** [comment]
The problem here is caused by the way we generate the function name for any JIT compiled function. The following code is compiled into multiple functions based on the value of the "free variable" `n_cols` that is used inside the function (welcome to template specialization in Numba :smile: ).

```python
def _make_write_values_kernel_func(n_cols):
    @dpex.func
    def write_values(array_in, row_idx):
        for idx in range(n_cols):
            array_in[row_idx, idx] = 1

    return write_values
```

In your example program, we "specialize" the `write_values` function on two `n_cols` values. Numba correctly generates two functions and in the Numba IR assigns them separate unique names. However, when the lowering from Numba to LLVM IR happens Numba is not using the unique name and generates two LLVM functions with the same name. Due to the same names, there is no way to distinguish between them and the linker randomly picks one. Thus, the wrong results.

We have a workaround that will fix it in numba-dpex.

@stuartarchibald In `NativeLowering`, the `FunctionDescriptor` uses the `qualname` instead of the `unique_name` that is infered from the Numba function IR. Is there a reason for it? To fix our issue, for now we are overriding the behaviour and forcing the `FunctionDescriptor` to use the `unique_name` by setting the qualname as the unique_name. Is there a better way to handle the issue?

**Comment by fcharras** [comment]
Great news and great debug :tada: , TY for following up. Ready to test the patch when it's out :grinning: 

> the linker randomly picks one

Now that you mention it, the bug was maybe already there in `numba == 0.19.0` and [this](https://github.com/soda-inria/sklearn-numba-dpex/blob/main/sklearn_numba_dpex/patches/load_numba_dpex.py) accidentally fixed it ? I noticed `__name__` or `__qualname__` were used somewhere, but I thought it was for caching. When bumping to post- #804 commits I removed this hack that might explain why the bug surfaced.

I never noticed it prior to `0.19.0` though.

**Comment by diptorupd** [comment]
@fcharras yes, the bug was there in 0.19 as well. Your patch must have been hiding it.

**Comment by diptorupd** [comment]
@fcharras Can you confirm if #905 fixes the issue?

**Comment by fcharras** [comment]
I've run a quick try with #905 . Outputs seem correct now but the benchmarks still show a huge slow down. I'd need a bit more time to understand what is going on.

**Comment by diptorupd** [comment]
@fcharras the slowdown issue should be addressed by #896.

**Comment by fcharras** [comment]
Unfortunately, the kmeans is still almost 100 times slower despite fixes in #896 :crying_cat_face: it seems that #905 was not enough. (will investigate, maybe there are issues with the user code)

**Comment by fcharras** [comment]
Issues cleared, there was some mistake in my setup that caused the 100x slowdown (apparently, activating the oneapi basekit interfers with `numba_dpex` in my environment :shrug: )

**Comment by stuartarchibald** [comment]
@diptorupd https://github.com/IntelPython/numba-dpex/issues/898#issuecomment-1420035680 sounds like a bug (I also saw something similar to this problem with derived IRs the other day). Do you think it will be reproducible in Numba alone or is this `numba-dpex` specific?

**Comment by diptorupd** [comment]
@chudur-budur can you try to replicate the issue with `numba.njit`? If the same issue exists, we should open an issue upstream and create a PR to apply the fix in the `NativeLowerer` so that we do not need the workaround in numba-dpex.

**Comment by chudur-budur** [comment]
> @chudur-budur can you try to replicate the issue with `numba.njit`? If the same issue exists, we should open an issue upstream and create a PR to apply the fix in the `NativeLowerer` so that we do not need the workaround in numba-dpex.

I am getting correct output on the latest main, just applied the latest `Range` kernel launch parameter syntax:

```python
import numba_dpex as dpex
import dpctl.tensor as dpt
from numba_dpex import Range


def make_write_values_kernel(n_rows):

    write_values = make_write_values_kernel_func()

    @dpex.kernel
    def write_values_kernel(array_in):
        for row_idx in range(n_rows):
            is_even = (row_idx % 2) == 0
            write_values(array_in, row_idx, is_even)

    return write_values_kernel[Range(1,1)]


def make_write_values_kernel_func():
    write_when_even = _make_write_values_kernel_func(4)
    write_when_odd = _make_write_values_kernel_func(2)

    @dpex.func
    def write_values(array_in, row_idx, is_even):
        if is_even:
            write_when_even(array_in, row_idx)
        else:
            write_when_odd(array_in, row_idx)

    return write_values


def _make_write_values_kernel_func(n_cols):
    @dpex.func
    def write_values(array_in, row_idx):
        for idx in range(n_cols):
            array_in[row_idx, idx] = 1

    return write_values


kernel = make_write_values_kernel(10)
array_in = dpt.empty(sh=(10, 10), dtype=dpt.int64)
kernel(array_in)
print(array_in)
```

This is the output:

```bash
[[1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]]
```

@fcharras if this issue is solved, could you please mark it as resolved?
