### ISSUE TITLE
JitKernel needs to be cleaned up

### ISSUE THREAD

**Issue by chudur-budur** [IntelPython/numba-dpex#901]
Due to mutiple iterations, the the [`JitKernel`](https://github.com/IntelPython/numba-dpex/blob/main/numba_dpex/core/kernel_interface/dispatcher.py#L56) class became messy. PR #896 

- There are at least two levels of caching for the same unspecialized kernel, i.e. `self._cache` and `self._kernel_bundle_cache`
- For the specialized kernel, the caching is done in three individual levels. i.e. `self._cache`, `self._kernel_bundle_cache` and `self._specialization_cache`
- These multiple levels of LRU caching is causing unnecessary overhead. Everything in that class needs to be made streamlined and clean. e.g. `self._cache` and `self._kernel_bundle_cache` can be consolidated.
- Also due to these reasons, the cache-hit/miss counts (`self._cache_hits`) became ambiguous. 
- Either `_check_range()` and `_check_ndrange()` functions need to be moved inside `Range`, `NdRange` class or moved into the `numba_dpex.core.kernel_interface.utils` module.

**Comment by diptorupd** [comment]
> * For the specialized kernel, the caching is done in three individual levels. i.e. `self._cache`, `self._kernel_bundle_cache` and `self._specialization_cache`

Specialized kernels do not use the `self._cache`.

**Comment by diptorupd** [comment]
Out of scope now as `JitKernel` will get replaced by `experimental.KernelDispatcher`
