### ISSUE TITLE
Atomics test cases fail on 4th gen Xeon CPU with OpenCL backend

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#986]
All test cases that verify atomic operations in `numba_dpex/tests/kernel_tests/test_atomic_op.py` fail with segmentation fault when run on 4th gen Xeon CPU (SPR) with OpenCL backend.

Hardware - Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8465C CPU
numba-dpex: 0.20.0
numba: 0.56.4
dpctl: 0.14.2
dpnp: 0.11.1

Failure log:
```
.conda/envs/dpep/lib/python3.9/site-packages/numba_dpex/tests/kernel_tests/test_atomic_op.py::test_kernel_atomic_simple[int32-kernel_result_pair0-opencl:cpu:0] Segmentation fault (core dumped)
```

**Comment by oleksandr-pavlyk** [comment]
Please provide output of `python -c "import dpctl; dpctl.select_cpu_device().print_device_info()"`

**Comment by adarshyoga** [comment]
There is no issue with atomic operations on CPU with `int32`. It looks the test file [`test_atomic_op.py`](https://github.com/IntelPython/numba-dpex/blob/dc255049bbc1aaaf1483410d00a0c68a3d5fbfb4/numba_dpex/tests/kernel_tests/test_atomic_op.py#L74) is not updated to follow CFD semantics. Here is the same test case after making CFD changes.

```
import numba_dpex as dpex
import dpnp as np

@dpex.kernel
def f(a):
    dpex.atomic.add(a, 0, 1)

a = np.zeros(100, dtype=np.int32)
print ("BEFORE: \n", a)
f[100, ](a)
print("AFTER: \n", a)
```

Here is the log (with trivial edits for brevity) from running this test case on 4th gen Xeon CPU with OpenCL backend.

```
:~> ONEAPI_DEVICE_SELECTOR=opencl:cpu:* python atomic_test.py
BEFORE:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

AFTER:
 [100   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]

```
