### ISSUE TITLE
When dpnp.empty() has been called twice outside of @dpjit, one of them invokes overloaded dpnp.empty() function

### ISSUE THREAD

**Issue by chudur-budur** [IntelPython/numba-dpex#998]
When `dpnp.empty()` function has been called outside of `@dpjit`, it invokes the overloaded [`ol_dpnp_empty()`](https://github.com/IntelPython/numba-dpex/blob/main/numba_dpex/dpnp_iface/arrayobj.py#L207) function. 

This happens only when the `dpnp.empty()` function has been called twice (or more), but doesn't happen when it's been called once.

How to reproduce:

1. Put a `print("Inside ol_dpnp_empty()")` inside the begining of [`ol_dpnp_empty()`](https://github.com/IntelPython/numba-dpex/blob/main/numba_dpex/dpnp_iface/arrayobj.py#L207) function.
2. Run the code below:

```python
import dpnp
import dpctl
from numba_dpex import dpjit

@dpjit
def func():
    # dpnp.empty() inside @dpjit
    A = dpnp.empty(10, dtype=dpnp.float32, usm_type="device", device="gpu") # prints "Inside ol_dpnp_empty()"
    return A
    
a = func()
print(a)

queue = dpctl.SyclQueue()
# dpnp.empty() outside @dpjit
C = dpnp.empty(10, dtype=dpnp.float32, usm_type="device", sycl_queue=queue) # prints "Inside ol_dpnp_empty()"
D = dpnp.empty(10, dtype=dpnp.float32, usm_type="device", sycl_queue=queue) # this does not

@dpjit
def func0(A, B):
    return A + B

a = func0(C, D)
print(a)
```

we get this output:
```bash
Inside ol_dpnp_empty()
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Inside ol_dpnp_empty()
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

But if we call `dpnp.empty()` outside `@dpjit` for only once, it doesn't call [`ol_dpnp_empty()`](https://github.com/IntelPython/numba-dpex/blob/main/numba_dpex/dpnp_iface/arrayobj.py#L207)

```python
import dpnp
import dpctl
from numba_dpex import dpjit

@dpjit
def func():
    A = dpnp.empty(10, dtype=dpnp.float32, usm_type="device", device="gpu")
    return A
    
a = func()
print(a)

queue = dpctl.SyclQueue()
C = dpnp.empty(10, dtype=dpnp.float32, usm_type="device", sycl_queue=queue)

@dpjit
def func0(A):
    return A

a = func0(C)
print(a)
```

we get this output:

```bash
Inside ol_dpnp_empty()
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

**Comment by diptorupd** [comment]
The first print is the `dpnp.empty` call inside `func`. The second print is from the `empty` call to create the returned array to store the output of `A+B` inside `func0`.
